module.exports = {
  docs: [
    'overview',
    {
      type: "category",
      label: "Installing Katan",
      items: [
        {
          type: "autogenerated",
          dirName: "installation"
        }
      ]
    },
    {
      type: "category",
      label: "Get started",
      items: [
        {
          type: "autogenerated",
          dirName: "getting-started"
        }
      ],
    },
    {
      type: "category",
      label: "CLI",
      items: [
        {
          type: "category",
          label: "Overview",
          collapsed: true,
          items: [
            {
              type: "autogenerated",
              dirName: "cli/overview",
            },
          ],
        },
        {
          type: "category",
          label: "Install and run",
          items: [
            {
              type: "autogenerated",
              dirName: "cli/install-and-run",
            },
          ],
        },
        "cli/update",
      ],
    },
    {
      type: "category",
      label: "Web User Interface",
      items: [
        "web-ui/introduction"
      ],
    },
    {
      type: "category",
      label: "Scaling Up",
      items: [
        "scaling-up/security"
      ]
    },
    {
      type: "doc",
      label: "FAQ",
      id: "faq"
    }
  ],
  reference: ["reference/overview"],
};
